@startuml

skinparam handwritten true
skinparam shadowing false

skinparam rectangle {
  BackgroundColor<<blue>> DodgerBlue
  BackgroundColor<<green>> ForestGreen
  BackgroundColor<<gray>> LightSlateGray
}

@enduml