#!/usr/bin/env bash
. $PLUGIN_LIB
PLUGIN_PRIORITY=0

on-initialize() {
  #
  # Add deployment unit configuration to environmental substition
  # sources as the first items to ensure these are available before
  # any additional sources
  #
  ln -s $ENVIRONMENT_CONFIGURATION $PLUGIN_SUBSTITION_DIR/01-global-environment.conf
  ln -s $PRODUCT_CONFIGURATION_DIR/product.conf $PLUGIN_SUBSTITION_DIR/02-product.conf
  writeBackwardsCompatibilityEnvironment $PLUGIN_SUBSTITION_DIR/04-backwards-compatibility.conf
  ln -s $DU_DIR/deployment.conf $PLUGIN_SUBSTITION_DIR/05-du-deployment.conf
  ln -s $DU_DIR/${ENVIRONMENT}.conf $PLUGIN_SUBSTITION_DIR/06-du-environment.conf
  return $PLUGIN_ENABLED
}

writeBackwardsCompatibilityEnvironment() {
  local file=$1
  cat > $file <<EOF
export NAMESPACE=$DU_NAMESPACE
export K8S_ENVIRONMENT=$ENVIRONMENT
export K8S_LOAD_BALANCER=$BLUE_LOAD_BALANCER
EOF
}

main "$@"
exit 1
