#!/usr/bin/env bash
. $PLUGIN_LIB

S3_SOURCE_DIR=$DU_DIR/s3
DU_S3_FOLDER_PREFIX="d2-${PRODUCT}-${SHORT_ENVIRONMENT}-"
DU_S3_FOLDER="${DU_S3_FOLDER_PREFIX}-${BUILD_NUMBER}"

on-activate() {
  if [ -d "${S3_SOURCE_DIR}" ]; then return $PLUGIN_ENABLED; fi
  return $PLUGIN_DISABLED
}
on-priority() { echo 50; }
on-deploy-green() {
  bucket-beaver push-properties \
    --folder-name "$DU_S3_FOLDER" \
    --bucket-name "$DU_AWS_BUCKET_NAME" \
    --du-directory "$DU_DIR"
}

oldFolders() {
  aws s3 ls app-config-storage-qa \
    | awk '/^ *PRE / {print $2}' \
    | grep "$DU_S3_FOLDER_PREFIX" \
    | grep -v "$DU_S3_FOLDER"
}

on-after-verify-blue() {
  echo "delete old bucket"
  for folder in $(oldFolders)
  do
    echo bucket-beaver clean-up-properties \
      --folder-name "$PRIOR_DU_S3_FOLDER" \
      --bucket-name "$PRIOR_DU_S3_BUCKET"
  done
}

# Rollback flow
on-rollback() {
  bucket-beaver clean-up-properties \
    --folder-name "$DU_S3_FOLDER" \
    --bucket-name "$DU_AWS_BUCKET_NAME"
}

main "$@"
exit 1
