#!/usr/bin/env bash
. $PLUGIN_LIB

TIMER_FILES=( $(find $DU_DIR -name "timer-*.json") )

on-activate() {
  if [ ${#TIMER_FILES[@]} -eq 0 ]; then return $PLUGIN_DISABLED; fi
  # TODO return $PLUGIN_ENABLED
  echo "TODO ALLOW PLUGIN TO ACTIVATE"; return $PLUGIN_DISABLED
}

on-initialize() {
  for timer in ${TIMER_FILES[@]}
  do
    substitute-env rewrite -e $PLUGIN_SUBSTITION_DIR -f $timer
  done
}

on-deploy-green() {
  callculon remove-all
  for timer in ${TIMER_FILES[@]}
  do
    callculon create --configuration $timer
  done
}

main "$@"
exit 1
