#!/usr/bin/env bash

#
# Provides short cut for using the deployer toolkit.
# The current directory is a deployment unit and will be mounted.
#
#
IMAGE=vasdvp/deployer-toolkit:latest

[ -z "$ENCRYPTION_PASSPHRASE" -a -n "$DU_CRYPTO_KEY" ] && ENCRYPTION_PASSPHRASE="$DU_CRYPTO_KEY"


operatingSystem="$(uname -o)"
case $operatingSystem in
	Msys) export MSYS_NO_PATHCONV=1;;
	cygwin|Cygwin) export MSYS_NO_PATHCONV=1;;
esac

if [ "${PULL:-true}" == true ]; then docker pull $IMAGE > /dev/null; fi
[ -z "${TERM}" ] && TERM=xterm
docker run --rm \
  -v $(pwd):/du \
  -e TERM="$TERM" \
  -e ENCRYPTION_PASSPHRASE="$ENCRYPTION_PASSPHRASE" \
  $IMAGE $@
