#!/usr/bin/env bash

#
# Provides short cut for using the deployer toolkit.
# The current directory is a deployment unit and will be mounted.
#
#
IMAGE=vasdvp/deployer-toolkit:latest

[ -z "$ENCRYPTION_PASSPHRASE" -a -n "$DU_CRYPTO_KEY" ] && ENCRYPTION_PASSPHRASE="$DU_CRYPTO_KEY"



if [ "${PULL:-true}" == true ]; then docker pull $IMAGE > /dev/null; fi
docker run -v $(pwd):/du -e ENCRYPTION_PASSPHRASE="$ENCRYPTION_PASSPHRASE" --rm $IMAGE $@
