---
apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $FACILITIES_VERSION
    deployment-test-status: UNTESTED
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: facilities-collector-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "150"
spec:
  rules:
    - http:
        paths:
          - path: /facilities-collector/.*
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: facilities-v0-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /v0/$1$2
spec:
  rules:
    - http:
        paths:
          - path: /va_facilities/v0/(facilities|nearby)(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: facilities-openapi-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /va_facilities/(docs/v0/api)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internal-facilities-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
    - http:
        paths:
          - path: /facilities/(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
