---
apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $INSURANCE_VERSION
    deployment-test-status: UNTESTED
---
# ToDo Resource Limits
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: insurance-internal-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /insurance/(.*)
            backend:
              serviceName: insurance
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: insurance-ingress
 namespace: $DU_NAMESPACE
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/rewrite-target: /$1/$2$3
spec:
  rules:
    - http:
        paths:
          - path: /fhir/v0/(r4)/(Coverage)($|/[^$].*)
            backend:
              serviceName: insurance
              servicePort: 80
