---
apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $PROMETHEUS_VERSION
    deployment-test-status: UNTESTED
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /prometheus/?(.*)
            backend:
              serviceName: prometheus-service
              servicePort: 8080
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-resource-quota
  namespace: $DU_NAMESPACE
spec:
  hard:
    limits.cpu: "2000m"
    limits.memory: "26.5G"
