---
apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $SC_VERSION
    deployment-test-status: UNTESTED
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smart-cards-fhir-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /r4/$2
spec:
  rules:
    - http:
        paths:
          - path: /fhir/v0/(dstu2|r4)/(Patient/[A-Z0-9]+/[$]HealthWallet[.]issueVc)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smart-cards-internal-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /smart-cards/(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
